Documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**/*
dependency-upgrade:
  - changed-files:
      - any-glob-to-any-file:
          - api-gateway/pom.xml
          - catalog-service/pom.xml
          - config-server/pom.xml
          - inventory-service/pom.xml
          - order-service/pom.xml
          - payment-service/pom.xml
          - service-registry/pom.xml
          - gatling-tests/pom.xml
