version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          memory: 350m
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microservice-network

  zipkin-server:
    image: openzipkin/zipkin
    deploy:
      resources:
        limits:
          memory: 512m
    expose:
      - "9411"
    ports:
      - "9411:9411"
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservice-network
      

  postgresqldb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservice-network

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db/mongo
    ports:
      - "27017:27017"
    networks:
      - microservice-network

  naming-server:
    image: dockertmt/mmv2-service-registry:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8761:8761"
    networks:
      - microservice-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  config-server:
    image: dockertmt/mmv2-config-server:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8888:8888"
    networks:
      - microservice-network

  api-gateway:
    image: dockertmt/mmv2-api-gateway:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8765:8765"
    networks:
      - microservice-network
    depends_on:
      - config-server
      - naming-server
      - rabbitmq
      - zipkin-server
      - mongo
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888/
      SPRING_DATA_MONGODB_HOST: mongo

  catalog-service:
    image: dockertmt/mmv2-catalog-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "18080:18080"
    networks:
      - microservice-network
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
      - postgresqldb
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_PROFILES_ACTIVE: prod

  inventory-service:
    image: dockertmt/mmv2-inventory-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "18181:18181"
    networks:
      - microservice-network
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
      - postgresqldb
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_PROFILES_ACTIVE: local

  order-service:
    image: dockertmt/mmv2-order-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "18282:18282"
    networks:
      - microservice-network
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
      - postgresqldb
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE= http://naming-server:8761/eureka
      - SPRING.ZIPKIN.BASEURL= http://zipkin-server:9411/
      - RABBIT_URI= amqp://guest:guest@rabbitmq:5672
      - SPRING_RABBITMQ_HOST= rabbitmq
      - SPRING_ZIPKIN_SENDER_TYPE= rabbit
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/appdb
      - SPRING_DATASOURCE_USERNAME=siva
      - SPRING_DATASOURCE_PASSWORD=secret

networks:
  microservice-network:

volumes:
  mongo-data:
