jwt:
  secret-key: ecf1222c-88fd-47f3-988f-bdd78bade1ad
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      metrics:
        enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
        wiretap: false
      routes:
        - id: order-service
          predicates:
            - Path=/order-service/**
          uri: lb://order-service
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenish-rate: 60
                  burst-capacity: 10
        - id: inventory-service
          predicates:
            - Path=/inventory-service/**
          uri: lb://inventory-service
          filters:
            - name: CircuitBreaker
              args:
                name: exampleSlowCircuitBreaker
                fallback-uri: forward:/fallback/api/inventory
        - id: catalog-service
          predicates:
            - Path=/catalog-service/**
          filters:
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  first-backoff: 50ms
                  max-backoff: 500ms
                  factor: 2
                  based-on-previous-value: true
          uri: lb://catalog-service
        - id: payment-service
          predicates:
            - Path=/payment-service/**
          uri: lb://payment-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}/"
  mustache:
    check-template-location: false
  webflux:
    problemdetails:
      enabled: true
#    base-path: /${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      catalog-service:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        register-health-indicator: true
  timelimiter:
    instances:
      catalog-service:
        timeout-duration: 3s

springdoc:
  cache:
    disabled: true
# We should display api-gateway as well
  swagger-ui:
    urls[0]:
      name: api-gateway
      url: /v3/api-docs
# adding this so that List<groupedopenapi> bean will trigger
  group-configs[0]:
    group: api-gateway
    paths-to-match: /**
#  packagesToScan: com.example.api.gateway.web
