jwt:
  secret-key: ecf1222c-88fd-47f3-988f-bdd78bade1ad
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      metrics:
        enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
      - id: order-service
        predicates:
        - Path=/order-service/**
        uri: lb://order-service
        filters:
        - CircuitBreaker=myCircuitBreaker
      - id: inventory-service
        predicates:
        - Path=/inventory-service/**
        uri: lb://inventory-service
      - id: catalog-service
        predicates:
        - Path=/catalog-service/**
        uri: lb://catalog-service
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}/"
  webflux:
    base-path: /${spring.application.name}

springdoc:
  cache:
    disabled: true
  packagesToScan: com.example.api.gateway.web
