apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Tempo
  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-micro-service
    access: proxy
    url: http://host.docker.internal:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo-micro-service
  - name: Tempo
    type: tempo
    uid: tempo-micro-service
    access: proxy
    url: http://tempo:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: prometheus-micro-service
        tags: [ { key: 'service.name', value: 'application' }, { key: 'org' }, { key: 'method' }, { key: 'uri' }, { key: 'outcome' }, { key: 'status' }, { key: 'exception' } ]
        queries:
          - name: 'Throughput'
            query: 'sum(rate(http_server_requests_seconds_count{$$__tags}[$$__rate_interval]))'
          - name: 'Latency'
            query: 'histogram_quantile(1.00, sum(rate(http_server_requests_seconds_bucket{$$__tags}[$$__rate_interval])) by (le))'
      tracesToLogs:
        datasourceUid: 'loki-micro-service'
        tags: [ 'instance', 'pod', 'namespace', 'hostname' ]
        mappedTags: [ { key: 'org' }, { key: 'service.name', value: 'application' }  ]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
        lokiSearch: true
      lokiSearch:
        datasourceUid: loki-micro-service
      serviceMap:
        datasourceUid: prometheus-micro-service
      search:
        hide: false
      nodeGraph:
        enabled: true
  - name: Loki
    type: loki
    uid: loki-micro-service
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo-micro-service
          matcherRegex: \[.+,(.+?),
          name: traceId
          url: $${__value.raw}