server:
  port: 18282
  servlet:
    context-path: /${spring.application.name}
  forward-headers-strategy: framework
spring:
  application:
    name: order-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: true
    streams:
      client-id: order-service-stream-client
      replication-factor: 1
      producer:
        acks: all
      application-id: ${spring.application.name}
      properties:
        commit:
          interval:
            ms: 100
        default:
          timestamp:
            extractor: org.apache.kafka.streams.processor.WallclockTimestampExtractor
          key:
            serde: org.apache.kafka.common.serialization.Serdes$LongSerde
          value:
            serde: org.springframework.kafka.support.serializer.JsonSerde
        spring:
          json:
            trusted:
              packages: 'com.example.common.dtos'
#      state-dir: /tmp/kafka-streams/
