server:
  port: 18282
  servlet:
    contextPath: /${spring.application.name}
  forward-headers-strategy: framework
spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888/
  liquibase:
    change-log: classpath:/db/migration/liquibase-changelog.xml

springdoc:
  packagesToScan: com.example.orderservice.web.controllers

spring.kafka:
  bootstrap-servers: 127.0.0.1:29092
  producer:
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  streams:
    properties:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
      default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
      spring.json.trusted.packages: "*"
    state-dir: /tmp/kafka-streams/
