eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jdbc:
  datasource-proxy:
    # enable and configure query logging
    query:
      # Enable logging all queries to the log.
      enable-logging: true
      # Severity of query logger.
      log-level: DEBUG
      # Name of query logger.
      logger-name: datasource-query-logger
    # Logging to use for logging queries.
    logging: slf4j
    # Use multiline output for logging query.
    multiline: false
    # How to Include the Bind Parameter Values in Spans
    include-parameter-values: false
    # Use json output for logging query.
    json-format: false
  # Specify jdbc.includes property. By default, the property is set to include(observe) all(CONNECTION, QUERY, FETCH) types.
  includes: connection,fetch,query
# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}]"
  level:
    datasource-query-logger: INFO
management:
  observations:
    key-values:
      application: ${spring.application.name}
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        resilience4j:
          circuitbreaker:
            calls: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info,loggers,metrics,refresh,prometheus,circuitbreakers,ratelimiters
  info:
    git:
      mode: full
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s
server:
  shutdown: graceful
spring:
  datasource:
    hikari:
      auto-commit: false
  jmx:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        jdbc:
          batch_size: 25
          lob:
            non_contextual_creation: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
          plan_cache_max_size: 4096
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 5
    # show-sql: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    problemdetails:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS
  threads:
    virtual:
      enabled: true

#SpringDoc Properties
springdoc:
  swagger-ui:
    #For sorting endpoints alphabetically
    operations-sorter: alpha
    #For sorting tags alphabetically
    tags-sorter: alpha
---
spring:
  config:
    activate:
      on-profile: "docker"
  datasource:
    password: secret
    url: jdbc:postgresql://postgresql:5432/appdb
    username: appuser
  kafka:
    bootstrap-servers:
    - kafka:29092
eureka:
  client:
    service-url:
      default-zone: http://naming-server:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans
---
spring:
  config:
    activate:
      on-profile: "native"
    import: optional:configserver:http://localhost:8888/
