server:
  port: 18181
  servlet:
    contextPath: /${spring.application.name}
spring:
  application:
    name: inventory-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}/"
  mvc:
    problemdetails:
      enabled: true
  testcontainers:
    beans:
      startup: parallel
  kafka:
# bootstrap-servers: 127.0.0.1:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.example.common.dtos"
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: true
  threads:
    virtual:
      enabled: true
