name: Master Branch CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvn clean install
