name: api-gateway

on:
  push:
    paths:
      - "api-gateway/**"
    branches: [main]
  pull_request:
    paths:
      - "api-gateway/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "microsoft"
          cache: "maven"

      - name: Start up softwares via Docker Compose
        run: |
          docker compose up rabbitmq zipkin-server mongo -d
          sleep 10
          docker ps -a

      - name: Build and analyze
        run: |
          cd api-gateway
          chmod +x mvnw
          ./mvnw clean package
