name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["17"]
    name: Build on Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.1.1
        with:
          java-version: ${{ matrix.java }}
          distribution: "adopt"
          cache: "maven"
      - name: Build with Maven and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DOCKER_PASSCODE: ${{secrets.DOCKER_PASSCODE}}
        run: mvn -B clean spring-boot:build-image -DCI_DOCKER_PASSWORD=${DOCKER_PASSCODE} -DCI_DOCKER_USERNAME=dockertmt -Dspring-boot.build-image.publish=true org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
