name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '16' ]
    name: Build on Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.3.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          # A directory to store and save the cache
          path: ~/.m2
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Build with Maven and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml


