name: payment-service

on:
  pull_request:
    paths:
      - "payment-service/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build on GraalVM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Start up softwares via Docker Compose
        run: |
          docker compose up zookeeper rabbitmq zipkin-server postgresql kafka -d
          sleep 10
          docker ps -a

      - name: Build and analyze
        run: |
          cd payment-service
          chmod +x mvnw
          ./mvnw -B -ntp clean -Pnative package -DskipTests
